spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userauthapp
    username: root
    password: userauthapp
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml